#!/bin/bash

echo "Enter a:"
read a
echo "Enter b:"
read b
echo "Enter c:"
read c
echo "Enter d:"
read d
echo "Enter e:"
read e
	sum = $a+$b+$c+$d+$e
	echo sum = $sum

	Avg = $sum/5
	echo Avg = $Avg

